### ISSUE TITLE
Research pokemon api functionality

### ISSUE THREAD

**Issue by jazzberriess** [jazzberriess/collab-what-pkmn-are-you#22]
Research pokemon api functionality

[PokéAPI](https://pokeapi.co/)

**Comment by AtlantaBlack** [comment]
### PokéAPI

[PokéAPI](https://pokeapi.co/)

PokéAPI is an enormous API that contains details of almost everything from the mainline games: berries, items, contests, attack types, Pokémon, etc. Each part of the API has its own URL, eg:

to access Berries:
`https://pokeapi.co/api/v2/berry/{id or name}/`

to access Pokémon moves: 
`https://pokeapi.co/api/v2/move/{id or name}/`

to access the Pokémon creatures themselves:
`https://pokeapi.co/api/v2/pokemon/{id or name}/`

For the MVP stage of our project, we will be concerned with calling only the specific Pokémon (see last example above).

The first call to the API returns an array in which there are two values: (1) Pokémon name, and (2) Pokémon URL.

<img width="474" alt="pokeapi-eg-first-call" src="https://user-images.githubusercontent.com/97859552/160953687-55432eeb-ce5d-4420-b1d4-9908771a3b45.png">

The second call to the API will target the Pokémon url, and from there we will be able to obtain data on the Pokémon's typing, which will then be used to compare to the genre of the user-selected artist.
