### ISSUE TITLE
Connect to Pokemon API (fetch Pokédata call one)

### ISSUE THREAD

**Issue by jazzberriess** [jazzberriess/collab-what-pkmn-are-you#23]
Connect to Pokemon API

**Comment by AtlantaBlack** [comment]
### Connecting to Pokémon API (first call)

Made fetch to pokéAPI to retrieve all creature data. The query limit was increased to full length `/?limit=1126` so every creature's data can be easily pulled. See image below for the console.log of successfully pulled data:

<img width="479" alt="connect-to-pokemon-api" src="https://user-images.githubusercontent.com/97859552/160976759-f7bbd6d4-83b8-45e0-a2e1-47cd3f8d2948.png">

**Comment by jazzberriess** [comment]
Looks like this one is complete :) Closing ticket.

**Comment by AtlantaBlack** [comment]
Pull request reference: #30
