### ISSUE TITLE
Add Modal functionality using JS

### ISSUE THREAD

**Issue by AtlantaBlack** [jazzberriess/collab-what-pkmn-are-you#46]
Add functionality to the modal: 

- make the modal appear on the screen when the user clicks on the pokeball 

- make the modal disappear if the user clicks anywhere outside the modal

- make the modal store the user input (artist name) into local storage

- close the modal when the user has submitted the artist name and show results

**Comment by jazzberriess** [comment]
Multiple pulls are referenced in this issue as the modal caused us some...problems.
